# Generated by Django 6.0 on 2025-12-17 06:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('main_image', models.ImageField(upload_to='projects/main/', verbose_name='Главное изображение')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('planned', 'Планируется'), ('archive', 'Архивный')], default='active', max_length=20, verbose_name='Статус проекта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('prize_fund', models.CharField(blank=True, max_length=255, verbose_name='Призовой фонд')),
                ('contacts', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projects/docs/', verbose_name='Положение / регламент')),
                ('external_link', models.URLField(blank=True, verbose_name='Ссылка на результаты')),
                ('gallery_link', models.URLField(blank=True, verbose_name='Ссылка на фотогалерею')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
