# Generated by Django 6.0 on 2025-12-17 06:28

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/', validators=[projects.validators.validate_project_file], verbose_name='Положение / регламент'),
        ),
    ]
