# Generated by Django 6.0 on 2025-12-17 06:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание'),
        ),
    ]
