# Generated by Django 6.0 on 2026-01-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.AddField(
            model_name='season',
            name='team_list_pdf',
            field=models.FileField(blank=True, null=True, upload_to='team_lists/', verbose_name='Список игроков PDF'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='player',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Год'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
