# Generated by Django 6.0 on 2025-12-17 07:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Полное описание'),
            preserve_default=False,
        ),
    ]
