# Generated by Django 6.0 on 2025-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('members', 'Члены федерации'), ('general_meeting', 'Общее собрание'), ('board', 'Правление'), ('chairman', 'Председатель'), ('vice_chairman', 'Заместители председателя'), ('secretary', 'Ответственный секретарь'), ('coaches_council', 'Тренерский совет'), ('audit_committee', 'Контрольно-счетная комиссия'), ('judges_committee', 'Судейская дисциплинарная комиссия')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons_photos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subdivisions', models.ManyToManyField(related_name='members', to='structure.subdivision')),
            ],
            options={
                'verbose_name': 'Член подраздела',
                'verbose_name_plural': 'Члены подразделов',
                'ordering': ['sort_order'],
            },
        ),
    ]
