# Generated by Django 6.0 on 2026-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О сотруднике'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='person',
            name='period',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subdivisions',
            field=models.ManyToManyField(related_name='members', to='structure.subdivision', verbose_name='Подразделения'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='title',
            field=models.CharField(choices=[('members', 'Члены федерации'), ('general_meeting', 'Общее собрание'), ('board', 'Правление'), ('chairman', 'Председатель'), ('vice_chairman', 'Заместители председателя'), ('secretary', 'Ответственный секретарь'), ('coaches_council', 'Тренерский совет'), ('audit_committee', 'Контрольно-счетная комиссия'), ('judges_committee', 'Судейская дисциплинарная комиссия')], max_length=50, unique=True, verbose_name='Подразделение'),
        ),
    ]
